'use client';
import type { ReactNode } from 'react';
const money=(n:number)=>new Intl.NumberFormat('en-IN',{maximumFractionDigits:0}).format(n||0);
const chartColors=['#1f4e79','#0f766e','#d97706','#be185d','#4f46e5','#65a30d','#c2410c','#0891b2','#7c3aed','#15803d','#dc2626','#a16207','#2563eb','#475569'];
const metricColors={sales:'#1f4e79',purchase:'#0f766e',expense:'#d97706'};
export function BarChart({data,title}:{data:{label:string;value:number}[];title:string}){const max=Math.max(1,...data.map(d=>d.value));return <div className="card chart-card"><div className="card-title">{title}</div><div className="bar-chart">{data.map((d,i)=><div className="bar-row" key={`${d.label}-${i}`}><div className="bar-label">{d.label}</div><div className="bar-track"><div className="bar-fill" style={{width:`${(d.value/max)*100}%`,backgroundColor:chartColors[i%chartColors.length]}}/></div><div className="bar-value">₹{money(d.value)}</div></div>)}</div></div>}
export function LineChart({data,title}:{data:{label:string;value:number}[];title:string}){const w=700,h=220,p=28;const max=Math.max(1,...data.map(d=>d.value));const pts=data.map((d,i)=>({x:p+(i*(w-2*p))/Math.max(1,data.length-1),y:h-p-(d.value/max)*(h-2*p)}));const path=pts.map((pt,i)=>(i?'L':'M')+pt.x.toFixed(1)+' '+pt.y.toFixed(1)).join(' ');return <div className="card chart-card"><div className="card-title">{title}</div><svg viewBox={`0 0 ${w} ${h}`} className="line-chart" role="img" aria-label={title}><defs><linearGradient id="line-area" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor={chartColors[1]} stopOpacity=".2"/><stop offset="100%" stopColor={chartColors[1]} stopOpacity="0"/></linearGradient></defs>{[0,1,2,3].map(i=><line key={i} x1={p} y1={p+i*(h-2*p)/3} x2={w-p} y2={p+i*(h-2*p)/3} stroke="#dbe5eb" strokeDasharray="3 5"/>)}<path d={`${path} L${pts.at(-1)?.x||p} ${h-p} L${pts[0]?.x||p} ${h-p} Z`} fill="url(#line-area)"/><path d={path} fill="none" stroke={chartColors[1]} strokeWidth="3" strokeLinejoin="round" strokeLinecap="round"/>{pts.map((pt,i)=><g key={i}><circle cx={pt.x} cy={pt.y} r="4" fill="#fff" stroke={chartColors[1]} strokeWidth="2"/><text x={pt.x} y={h-8} textAnchor="middle" fontSize="10">{data[i].label}</text></g>)}</svg></div>}
type LineSeries = { key: string; label: string; color: string };
export function MultiLineChart({data,title,series}:{data:Array<{label:string;[key:string]:string|number}>;title:string;series:LineSeries[]}){
	const w=700,h=220,p=30;
	const values=data.flatMap(point=>series.map(item=>Number(point[item.key]||0)));
	const min=Math.min(0,...values),max=Math.max(1,...values),range=max-min||1;
	const xAt=(index:number)=>p+(index*(w-2*p))/Math.max(1,data.length-1);
	const yAt=(value:number)=>p+((max-value)/range)*(h-2*p);
	return <div className="card chart-card"><div className="card-title">{title}</div><svg viewBox={`0 0 ${w} ${h}`} className="line-chart" role="img" aria-label={title}>
		{[0,1,2,3].map(index=>{const y=p+index*(h-2*p)/3;return <line key={index} x1={p} y1={y} x2={w-p} y2={y} stroke="#dbe5eb" strokeDasharray="3 5"/>})}
		{series.map(item=>{const points=data.map((point,index)=>({x:xAt(index),y:yAt(Number(point[item.key]||0))}));const path=points.map((point,index)=>(index?'L':'M')+point.x.toFixed(1)+' '+point.y.toFixed(1)).join(' ');return <g key={item.key}>
			<path d={path} fill="none" stroke={item.color} strokeWidth="3" strokeLinejoin="round" strokeLinecap="round"/>
			{points.map((point,index)=><circle key={`${item.key}-${index}`} cx={point.x} cy={point.y} r="3.5" fill="#fff" stroke={item.color} strokeWidth="2"/>)}
		</g>})}
		{data.map((point,index)=><text key={`${point.label}-${index}`} x={xAt(index)} y={h-8} textAnchor="middle" fontSize="10" fill="#6b7c8f">{point.label}</text>)}
	</svg><div className="multi-line-legend">{series.map(item=><span key={item.key}><i style={{backgroundColor:item.color}}/>{item.label}</span>)}</div></div>;
}
export function StackedMetricChart({data,title}:{data:{label:string;sales:number;purchases:number;expenses:number}[];title:string}){const max=Math.max(1,...data.flatMap(d=>[d.sales,d.purchases,d.expenses]));return <div className="card chart-card"><div className="card-title">{title}</div><div className="stack-chart">{data.map(d=><div key={d.label} className="stack-col"><div className="stack-area"><div className="seg sales" style={{height:`${d.sales/max*100}%`,backgroundColor:metricColors.sales}}/><div className="seg purchase" style={{height:`${d.purchases/max*100}%`,backgroundColor:metricColors.purchase}}/><div className="seg expense" style={{height:`${d.expenses/max*100}%`,backgroundColor:metricColors.expense}}/></div><span>{d.label}</span></div>)}</div><div className="legend"><span><i className="sales" style={{backgroundColor:metricColors.sales}}/>Sales</span><span><i className="purchase" style={{backgroundColor:metricColors.purchase}}/>Purchases</span><span><i className="expense" style={{backgroundColor:metricColors.expense}}/>Expenses</span></div></div>}
export function DonutChartContent({segments,colors=chartColors}:{segments:{label:string;value:number}[];colors?:string[]}){const total=Math.max(1,segments.reduce((a,b)=>a+b.value,0));let cursor=0;return <div className="donut-wrap"><svg viewBox="0 0 120 120" className="donut" role="img" aria-label={segments.map(segment=>`${segment.label}: ₹${money(segment.value)}`).join(', ')}><circle cx="60" cy="60" r="44" fill="none" stroke="#eef2f7" strokeWidth="18"/>{segments.map((s,i)=>{const pct=s.value/total;const dash=pct*276.46;const off=cursor*276.46;cursor+=pct;return <circle key={s.label} cx="60" cy="60" r="44" fill="none" stroke={colors[i%colors.length]} strokeWidth="18" strokeDasharray={`${dash} ${276.46-dash}`} strokeDashoffset={-off} transform="rotate(-90 60 60)"/>})}</svg><div className="donut-legend">{segments.map((s,i)=><div key={s.label}><span style={{background:colors[i%colors.length]}}/>{s.label}<b>₹{money(s.value)}</b></div>)}</div></div>}
export function DonutChart({segments,title}:{segments:{label:string;value:number}[];title:string}){return <div className="card chart-card donut-card"><div className="card-title">{title}</div><DonutChartContent segments={segments}/></div>}
export function KPI({title,value,sub}:{title:string;value:ReactNode;sub?:ReactNode}){return <div className="kpi card"><div className="kpi-label">{title}</div><div className="kpi-value">{value}</div>{sub&&<div className="kpi-sub">{sub}</div>}</div>}
